// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eijofhqetwrsnrnxsxnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpam9maHFldHdyc25ybnhzeG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjQ1OTMsImV4cCI6MjA2OTU0MDU5M30.-170u53YIHpPPzrXzoP_ViVphttgM8x8q_BLfeS4bjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});